clusterNames:
  - ${cluster1}
  - ${cluster2}
  - ${cluster3}

infrastructure: ${infrastructure}  

global_base_domain: ${global_base_domain}  


cockroachdb:
  image:
    repository: cockroachdb/cockroach
    tag: "v21.1.7"
    # repository: cockroachdb/cockroach-unstable
    # tag: "v21.1.0-rc.2"    
  cluster: ${cluster}
  uid: ${uid}
  conf:
    cache: 8GiB
    max-sql-memory: 8GiB
    join: 
      - cockroachdb-0.${cluster1}.cockroachdb.multicluster-cockroachdb.svc.clusterset.local
      - cockroachdb-1.${cluster1}.cockroachdb.multicluster-cockroachdb.svc.clusterset.local
      - cockroachdb-2.${cluster1}.cockroachdb.multicluster-cockroachdb.svc.clusterset.local
      - cockroachdb-0.${cluster2}.cockroachdb.multicluster-cockroachdb.svc.clusterset.local
      - cockroachdb-1.${cluster2}.cockroachdb.multicluster-cockroachdb.svc.clusterset.local
      - cockroachdb-2.${cluster2}.cockroachdb.multicluster-cockroachdb.svc.clusterset.local
      - cockroachdb-0.${cluster3}.cockroachdb.multicluster-cockroachdb.svc.clusterset.local
      - cockroachdb-1.${cluster3}.cockroachdb.multicluster-cockroachdb.svc.clusterset.local
      - cockroachdb-2.${cluster3}.cockroachdb.multicluster-cockroachdb.svc.clusterset.local
  fullnameOverride: cockroachdb
  statefulset:
    replicas: 3
    tolerations:
      - key: "workload"
        operator: "Equal"
        value: "cockroach"
        effect: "NoSchedule"
    nodeSelector:
      workload: cockroach    
  
  tls:
    enabled: yes
    certs:
      provided: yes
      tlsSecret: yes
      nodeSecret: cockroachdb-tls
